### ISSUE TITLE
Rounding modes

### ISSUE THREAD

**Issue by ConradSelig** [ConradSelig/cliStocksTracker#11]
Currently this project uses Pythons default round() function, but I found that my stock broker (I use Schwab) always rounds down, which means that the numbers this program outputs can be incorrect.

Two rounding modes we should support:
* "Math" rounding: 1.4 -> 1, 1.5 -> 2
* "Down" rounding: 1.4 ->1, 1.5 -> 1

I suppose we could support "Up" rounding as well, but lets be honest - nobody would use that, which is why I didn't bother listing it.

**Comment by yonMaor** [comment]
Hi, is there more information on this issue?

**Comment by ConradSelig** [comment]
@yonMaor Currently no, I suppose this isn't really enough information to get started.

Currently both stock counts and stock values are stored with as many decimal places as possible to retain accuracy, however, displaying a dollar amount with a dozen decimal places doesn't make a lot of sense!
That's why we round all float values down to two decimal places when printing, this ticket is about determining how that rounding is done.

One to two functions should be created to close this ticket, they should look similar to the following prototypes:
1 function:
```
def round_value(mode: str, value: float) -> float:
```
('mode' could also be an Enum instead of a string)
2 functions:
```
def math_round(value: float) -> float:
def down_round(value: float) -> float:
```
Just a starting place for these functions, feel free to implement differently if you have a better idea.

Which rounding mode should be chosen from the 'config' file, under the kwargs section -> should add another key so the config file looks like this:
```
...
kwargs:
        ...
        rounding_mode: [ math || down ]
        ...
...
```

---

Hope that it enough information for you to get started. Let me know if you have any additional questions.

**Comment by ConradSelig** [comment]
One more thing to add in - I don't want to limit future programmers to only rounding to two decimal places, so the function should also take the desired number of places to round to. Just like the native round() function: `round(val, places)`

**Comment by yonMaor** [comment]
Hey, could you assign the issue to me? I'll only be able to work on it during the coming weekend, but I'll be able to complete it then

**Comment by ConradSelig** [comment]
Let me know if you have any questions!

**Comment by yonMaor** [comment]
Two additional questions I have:
1. Could you upload the config and stock config files? Just wanna make sure that I'm working with the correct files (currently they are in the gitignore list.
2. Where do you want me to add the function? A seperate file, or within one of the classes?

**Comment by ConradSelig** [comment]
I've been intentionally keeping the config files out of the repo - just because they are so personalized. I'll upload a sample here however, so you can look at them anyways.

The rounding functions are not class specific, so if you put them in cliStocksTracker.py put them outside of the classes as standalone functions. Otherwise if you want to make a utils.py (or similar), go ahead! I'll leave that choice up to you.

Here are those config files, I've had to add the .txt extension for Github - but the config files don't have an extension:
[config.txt](https://github.com/ConradSelig/cliStocksTracker/files/6014361/config.txt)
[stocks_config.txt](https://github.com/ConradSelig/cliStocksTracker/files/6014362/stocks_config.txt)

**Comment by ConradSelig** [comment]
A checklist for ticket completion:
- [ ] Implement new rounding function(s).
- [ ] Refactor all existing calls of native round() to the new functions (using whatever mode the user has specified in the config file).
- [ ] Update README.md to include references to the new round functionality in the config files.

**Comment by yonMaor** [comment]
Is the number of digits to keep after the decimal point also determined in the config file?

**Comment by ConradSelig** [comment]
No, let the programmer decide that for each case.

**Comment by yonMaor** [comment]
Done. 
Please let me know if you have any comments, or if I've messed anything up :)

**Comment by ConradSelig** [comment]
Perfect. Changes merged.

Reference: #15 

Well done!
