### ISSUE TITLE
Buying / Selling stocks at multiple prices

### ISSUE THREAD

**Issue by ConradSelig** [ConradSelig/cliStocksTracker#5]
Currently tracking a stock allows for a single "total owned" value and a single "bought at" value, meaning if multiple shares of the same stock are purchased at different prices - the user has to manually take an average of the purchase prices to get decent portfolio data.

I'm not yet best sure how to best implement this. The multiple config files are already messy enough as is, and adding a line or two for every purchase would become unmanageable quite quickly.

Adding the "help wanted" label to this ticket as I am currently taking suggestions for implementation of this feature.

**Comment by ConradSelig** [comment]
@yonMaor Would you like to do a little testing for me? This was a huge change and chances are pretty good I've missed an edge case...
Just poke around the new feature and see if you can get the program to crash / do something unexpected.

**Comment by yonMaor** [comment]
@ConradSelig I'm game, but I've never done any testing so I might need some guidance here.

**Comment by yonMaor** [comment]
Ok, so before I start testing I think I need to undestand a little more about this feature, do you have anything specific you want tested, or should I just play around with it?

**Comment by ConradSelig** [comment]
@yonMaor You'll want to do a combination of black-box followed by glass-box testing to make sure to hit as many test cases as possible. Have you heard those terms before?

**Comment by patrick-hovsepian** [comment]
It would be great to start exploring adding unit tests to the various modules. My python experience is pretty limited so I'm not aware of any frameworks offhand but I'm sure there are plenty we could leverage.

**Comment by ConradSelig** [comment]
I'm looking at writing a proper testing suite right now!

I want something that can integrate with github so everyone is on the same page regarding test coverage. I'll make a new ticket once I've narrowed down the options to something I like.

**Comment by ConradSelig** [comment]
I'm closing this ticket - testing suite should pick up any last bugs in this ticket (and this feature has been around long enough I can confidently say it is working).
